---
ignores: # If found in path contained elements will be ignored
- node_modules
- ".git"

templating: ## Add your own values they will be replaced in fileSpecs and source licenseFile
  AUTHOR_NAME: "Pryv S.A."
  AUTHOR_EMAIL: info@pryv.com
  AUTHOR_WEB: https://pryv.com
  DESCRIPTION: "This package is part of Open Pryv.io"
  HOMEPAGE: https://pryv.com
  SPDX: BSD-3-Clause

license:
  year: ## Year value will be computed in the template as "YEARS" if start == end it will be just start otherwise START - END
    start: 2020
    end: CURRENT_YEAR

fileSpecs:

  package.json: # For package.json 
    json:
      force:  # Following fields will be replaced anyway
        private: false